---
abstract: 'Perl Interface to the CloudApp REST API'
author:
  - 'Matthias Dietrich <perl@rainboxx.de>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Module::Load: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Types::DateTimeX: 0
  MooseX::Types::URI: 0
  Readonly: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CloudApp-REST
provides:
  CloudApp::REST:
    file: lib/CloudApp/REST.pm
    version: 0.02
  CloudApp::REST::Item:
    file: lib/CloudApp/REST/Item.pm
  CloudApp::REST::Item::Archive:
    file: lib/CloudApp/REST/Item/Archive.pm
  CloudApp::REST::Item::Audio:
    file: lib/CloudApp/REST/Item/Audio.pm
  CloudApp::REST::Item::Bookmark:
    file: lib/CloudApp/REST/Item/Bookmark.pm
  CloudApp::REST::Item::Image:
    file: lib/CloudApp/REST/Item/Image.pm
  CloudApp::REST::Item::Pdf:
    file: lib/CloudApp/REST/Item/Pdf.pm
  CloudApp::REST::Item::Text:
    file: lib/CloudApp/REST/Item/Text.pm
  CloudApp::REST::Item::Unknown:
    file: lib/CloudApp/REST/Item/Unknown.pm
  CloudApp::REST::Item::Video:
    file: lib/CloudApp/REST/Item/Video.pm
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rainboxx/CloudApp-REST/
version: 0.02
